on:
   push:
     branches:
       - master
name: release-please
jobs:
 release-please:
   runs-on: ubuntu-latest
   steps:
     - uses: GoogleCloudPlatform/release-please-action@v2.5.6
       with:
         token: ${{ secrets.GITHUB_TOKEN }}
         release-type: node
     - uses: EndBug/latest-tag@latest
       with:
         description: This tag always points to the latest version
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
